"""Private, short-lived ECDSA certificates for WebTransport certificate hashes."""
import base64
import hashlib
import os
from pathlib import Path
import ssl
import subprocess
import tempfile
from utils.atomic_json import locked


def ensure_certificate(directory):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    if directory.is_symlink():
        raise ValueError("Certificate directory cannot be a symlink")
    os.chmod(directory, 0o700)
    cert, key = directory / "cert.pem", directory / "key.pem"
    with locked(directory / "certificate"):
        valid = False
        if cert.is_symlink() or key.is_symlink():
            raise ValueError("Certificate files cannot be symlinks")
        if cert.is_file() and key.is_file():
            try:
                text = subprocess.check_output(["openssl", "x509", "-in", str(cert), "-noout", "-text"],
                                               timeout=5, env={"PATH": "/usr/bin:/bin", "LC_ALL": "C"}).decode()
                # Only reuse certificates generated by this helper (10-day validity).
                marker = directory / "ecdsa-v1"
                valid = (marker.is_file() and "prime256v1" in text and
                         subprocess.run(["openssl", "x509", "-in", str(cert), "-checkend", "86400", "-noout"],
                                        capture_output=True, timeout=5).returncode == 0)
                if valid:
                    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
                    context.load_cert_chain(cert, key)
            except (OSError, subprocess.SubprocessError, ssl.SSLError):
                valid = False
        if not valid:
            with tempfile.TemporaryDirectory(dir=directory) as temporary:
                c, k = Path(temporary) / "cert.pem", Path(temporary) / "key.pem"
                subprocess.run(["openssl", "req", "-x509", "-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:prime256v1",
                                "-sha256", "-nodes", "-days", "10", "-subj", "/CN=BigCam",
                                "-addext", "subjectAltName=DNS:bigcam.local,IP:127.0.0.1",
                                "-keyout", str(k), "-out", str(c)],
                               capture_output=True, check=True, timeout=10,
                               env={"PATH": "/usr/bin:/bin", "LC_ALL": "C"})
                os.chmod(k, 0o600)
                os.chmod(c, 0o600)
                os.replace(k, key)
                os.replace(c, cert)
                (directory / "ecdsa-v1").touch(mode=0o600)
        os.chmod(key, 0o600)
        os.chmod(cert, 0o600)
    der = ssl.PEM_cert_to_DER_cert(cert.read_text())
    digest = base64.b64encode(hashlib.sha256(der).digest()).decode("ascii")
    return str(cert), str(key), digest
